Repository sdss/lvmdrp, pull requests merged in 2024-08, with the labels that each got.

#128 fixes skytable mjd bug
  python/lvmdrp/functions/skyMethod.py
Labels: bug

#129 Improving wavelength/LSF fitting routines
  bin/pix2wave
  python/lvmdrp/core/fiberrows.py
  python/lvmdrp/core/fit_profile.py
  python/lvmdrp/core/plot.py
  python/lvmdrp/core/rss.py
  python/lvmdrp/core/spectrum1d.py
  python/lvmdrp/etc/wavelength/lvm-pixwav-neon_hgne_argon_xenon_z1.txt
  python/lvmdrp/etc/wavelength/lvm-pixwav-neon_hgne_argon_xenon_z2.txt
  python/lvmdrp/etc/wavelength/lvm-pixwav-neon_hgne_argon_xenon_z3.txt
  python/lvmdrp/functions/imageMethod.py
  python/lvmdrp/functions/rssMethod.py
  python/lvmdrp/functions/run_calseq.py
  python/lvmdrp/main.py
Labels: bug, enhancement

#144 Improving calibrations
  bin/pix2wave
  python/lvmdrp/core/fiberrows.py
  python/lvmdrp/core/fit_profile.py
  python/lvmdrp/core/image.py
  python/lvmdrp/core/spectrum1d.py
  python/lvmdrp/core/tracemask.py
  python/lvmdrp/etc/wavelength/lvm-pixwav-neon_hgne_argon_xenon_b1.txt
  python/lvmdrp/etc/wavelength/lvm-pixwav-neon_hgne_argon_xenon_b2.txt
  python/lvmdrp/etc/wavelength/lvm-pixwav-neon_hgne_argon_xenon_b3.txt
  python/lvmdrp/functions/rssMethod.py
  python/lvmdrp/functions/run_calseq.py
Labels: enhancement
