Repository sdss/lvmdrp, pull requests merged in 2024-05, with the labels that each got.

#65 Create an initial drpall summary file
  .github/workflows/test.yaml
  README.md
  python/lvmdrp/functions/run_quickdrp.py
  python/lvmdrp/utils/metadata.py
  setup.cfg
Labels: enhancement

#84 Implementing nightly reductions & other fixes
  bin/drp
  examples/lco_com/cosmics.ipynb
  examples/lco_com/pixelflats.ipynb
  python/lvmdrp/core/fit_profile.py
  python/lvmdrp/core/image.py
  python/lvmdrp/core/rss.py
  python/lvmdrp/core/spectrum1d.py
  python/lvmdrp/etc/dataproducts/lvmFlat_bp.yaml
  python/lvmdrp/functions/imageMethod.py
  python/lvmdrp/functions/rssMethod.py
  python/lvmdrp/functions/run_calseq.py
  python/lvmdrp/functions/run_quickdrp.py
  python/lvmdrp/functions/run_twilights.py
  tests/functions/test_imageMethod.py
Labels: bug, enhancement

#87 Long-term calibration sequence
  bin/drp
  python/lvmdrp/core/constants.py
  python/lvmdrp/core/fiberrows.py
  python/lvmdrp/core/fluxcal.py
  python/lvmdrp/core/image.py
  python/lvmdrp/core/spectrum1d.py
  python/lvmdrp/etc/wavelength/lvm-pixwav-neon_hgne_argon_xenon_b2.txt
  python/lvmdrp/functions/fluxCalMethod.py
  python/lvmdrp/functions/imageMethod.py
  python/lvmdrp/functions/rssMethod.py
  python/lvmdrp/functions/run_calseq.py
  python/lvmdrp/functions/run_quickdrp.py
  python/lvmdrp/functions/run_twilights.py
  tests/functions/test_runtwilights.py
Labels: bug, enhancement

#99 updating exposed std sequence plots & fixing conditionals
  python/lvmdrp/functions/run_calseq.py
Labels: bug, enhancement

#100 Fixing missing information on RA, DEC and PA header keywords
  python/lvmdrp/functions/imageMethod.py
Labels: bug

#101 Optimizing spectra extraction
  python/lvmdrp/core/image.py
  python/lvmdrp/core/spectrum1d.py
  python/lvmdrp/functions/imageMethod.py
  python/lvmdrp/functions/run_calseq.py
  python/lvmdrp/main.py
Labels: enhancement
